name: Deploy Staging(firebase hosting)

on: push
jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - name: Install yarn and Build
        working-directory: ./src
        run: |
          yarn install
          yarn generate
      - name: Ready to Deploy
        working-directory: ./src
        run: yarn install -g firebase-tools
      - name: Deploy to firebase
        working-directory: ./src
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --only hosting
